# Generated by Django 4.1.3 on 2022-12-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tribeuser_banished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribeuser',
            name='banished',
            field=models.BooleanField(default=False),
        ),
    ]
