# Generated by Django 4.1.4 on 2022-12-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tribe',
            field=models.CharField(default='blap', max_length=100),
            preserve_default=False,
        ),
    ]
